default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: recruitment_task_dev
  username: rob
  password: password

test:
  <<: *default
  database: recruitment_task_test
  username: rob
  password: password

